version: '3'

services:
  server:
    build: server/
    environment: 
      APP_PORT: 8000
      MODEL_URL: http://ai_module:8001
      DB_URL: http://db
    ports:
      - 8000:8000
    volumes:
      - ./server:/user/src/app
  
  ai_module:
    build: ai_module/
    environment: 
      APP_PORT: 8001
    volumes:
      - ./ai_module:/user/src/app
      - ./images:/user/src/app/images

  db:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z